name: sarand
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - rgi
  - prokka
  - blast
  - biopython
  - numpy
  - pandas
  - matplotlib
  - gfapy
  - bandage
  - pillow
  - dna_features_viewer
  - pyyaml
