name: sarand
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - rgi
  - prokka
  - art
  - bandage
  - blast
  - biopython
  - numpy
  - pandas
  - matplotlib
  - gfapy
  - pillow
  - dna_features_viewer
  - spades
  - pyyaml
