---
PROKKA_COMMAND_PREFIX: ''

#the main dir to retrieve required files
#main_dir: 'test/'
main_dir: 'test/'
# the path of the fasta file containing all AMR sequences;
#If empty the one installed with Sarand (from CARD DB) will be used
amr_db: ''
# the threshold used for amr alignment: a hit is returned if identity/coverage >= threshold
amr_identity_threshold:  95
# the ddress of reference genomes that AMR genome will be inserted in them
#Provide either the absolute path or the path from main_dir
ref_genome_files: 'metagenome_data/'
#ref_genome_files: main_dir + 'H_S001__insert_180_gsa_anonymous.fasta'
# the length of AMR gene's neighbourhood to be extracted
seq_length: 1000
# Whether to contribute RGI annotation in Prokka result
use_RGI: true
# Whether to include loose cases in RGI result
RGI_include_loose: false
