---
PROKKA_COMMAND_PREFIX: ''

#the main dir to retrieve required files
#main_dir: 'test/'
main_dir: 'test/'
# the path of the fasta file containing all AMR sequences;
#If empty the one installed with Sarand (from CARD DB) will be used
amr_db: ''
# the threshold used for amr alignment: a hit is returned if identity/coverage >= threshold
amr_identity_threshold:  95
# Whether we have access to reference genome(s)
ref_genomes_available: true
# the address of the file containing contigs after assembly
#Provide either the absolute path or the path from main_dir
contig_file:  'spade_output/contigs.fasta'
# the length of AMR gene's neighbourhood to be extracted
seq_length: 1000
# Whether to contribute RGI annotation in Prokka result
use_RGI: true
# Whether to include loose cases in RGI result
RGI_include_loose: false
