name: test_package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run all
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Install bioconda dependencies"
        run: |
             mamba env create -f conda_env.yaml; 
             mamba activate sarand
      - name: "Install sarand"
        shell: bash -l {0}
        run: pip install .
      - name: "Run test"
        shell: bash -l {0}
        run: bash test/test.sh
